version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - aws s3 sync s3://gadna.media2 s3://$TARGET_BUCKET
      - aws s3 sync build s3://$TARGET_BUCKET

cache:
  paths:
    - node_modules/**/*
